### ISSUE TITLE
运行后没有结果，请问是什么原因？

### ISSUE THREAD

**Issue by keno-log** [duoyang666/ai_novel#1]
C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\langchain_core\_api\deprecation.py:139: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use RunnableSequence, e.g., `prompt | llm` instead.
  warn_deprecated(

**Comment by duoyang666** [comment]
我的问题，我是在本地电脑运行的，我的环境用了pyenv

**Comment by duoyang666** [comment]
https://mp.weixin.qq.com/s/bw9sUJidGsRZEneP9GXhuw

已完成
